/*
 * This file is generated by jOOQ.
*/
package com.example;


import com.example.tables.Another;
import com.example.tables.SchemaVersion;
import com.example.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>another</code>.
     */
    public static final Another ANOTHER = com.example.tables.Another.ANOTHER;

    /**
     * The table <code>schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.example.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>test</code>.
     */
    public static final Test TEST = com.example.tables.Test.TEST;
}
